# Generated by Django 3.0 on 2020-01-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20200104_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='photo',
        ),
    ]
