# Generated by Django 3.0 on 2019-12-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('established', models.DateField()),
                ('photo', models.ImageField(upload_to='faculty/')),
                ('about', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
