# Generated by Django 3.0 on 2020-01-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
